#version: '3.8'

services:
  
  python_app:
    container_name: python_app
    build:
      dockerfile: Dockerfile_python
    depends_on:
      - db
    ports:
      - '8888:8888'
  
  db:
    image: postgres:17 
    container_name: posgre_sql    
    ports:
      - '5432:5432'
    env_file:
      - ./env_db.dev
  
volumes:
  postgres_data: